### ISSUE TITLE
Feature this component on the pp docs

### ISSUE THREAD

**Issue by sbrugman** [Ghasel/streamlit-pandas-profiling#2]
Hi @Ghasel and @tconkling ,

Thanks for creating this component. Would you be interested in featuring it in the pandas-profiling docs? Linking the repo from the docs with a short description would provide it with some visibility.

A logical place to place it would be under integrations: 
 https://pandas-profiling.github.io/pandas-profiling/docs/master/rtd/pages/integrations.html#streamlit-panel. Changing the text shouldn't take much effort and can be as simple as a pull request with the changed .rst file.

Best,
Simon

**Comment by Ghasel** [comment]
Hello @sbrugman ,

Thank you for this suggestion, that's a great idea! I'll work on it this week-end.

Regards,
Syn
